global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'gestore_conservatorio'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['core-service:8081', 'notification-service:8082', 'room-booking-service:8083']