name: Java CI with Maven & Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#Permissions needed to write to the GitHub Package Registry (GHCR)
permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    #Download the code
    - name: Checkout repository
      uses: actions/checkout@v4

    #Prepare Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    #Compile and Test Microservices (Create files .jar)
    
    - name: Build Core Service
      run: mvn -B clean package -f CoreService/pom.xml

    - name: Build Notification Service
      run: mvn -B clean package -f NotificationService/pom.xml -DskipTests

    - name: Build Room Booking Service
      run: mvn -B clean package -f RoomBookingService/pom.xml -DskipTests

    #Prepare Docker environment: change the username to lowercase (required for Docker)
    - name: Lowercase Registry Owner
      run: |
        echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    #Build & Push Docker Images
    
    #Core Service
    - name: Build and push Core Service Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./CoreService
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/gestore-conservatorio-core:latest

    #Notification Service
    - name: Build and push Notification Service Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./NotificationService
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/gestore-conservatorio-notification:latest

    #Room Booking Service
    - name: Build and push Room Booking Service Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./RoomBookingService
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/gestore-conservatorio-booking:latest